/**
 * Needed this for a pre-build stage.
 *
 * download app-ids, parse it and compile a js hashset for quick retrival when determining jumplists sources.
 *
 * - ash
 * */

const { fetchUrl: get } = require("fetch");
const fs = require("fs");

const url =
  "https://raw.githubusercontent.com/EricZimmerman/JumpList/master/JumpList/Resources/AppIDs.txt";

get(url, (error, meta, body) => {
  const rows = body.toString().match(/^([\w\d]+)\|(.*)$/gim);
  if (!rows) {
    throw "Could not extract app-ids. Check if the format has changed.";
  }

  const ids = rows.map(e => e.split("|"));
  const hashset = ids.reduce((prev, [id, name]) => {
    prev[id] = name;
    return prev;
  }, {});

  // todo - log output, check length 
  fs.writeFileSync(
    "src/app-ids/compiled.js",
    `/* autogenerated by compile-appids.js */ module.exports = ${JSON.stringify(
      hashset
    )} `
  );
});
